### ISSUE TITLE
error in surface_mesh.py, line 30

### ISSUE THREAD

**Issue by sazearte** [croxis/SpaceDrive#1]
Hello i have this error when i try to use your code :

```
 File "surface_mesh.py", line 30, in <module>
    array.addColumn(InternalName.make('vertex'), 3, Geom.NTFloat32, Geom.CPoint)
TypeError: Arguments must match:
make(string str)
make(str name, int index)
```

**Comment by croxis** [comment]
Are you using Python 2 or 3?

**Comment by sazearte** [comment]
Panda with Python 2.7

**Comment by croxis** [comment]
I rewrote it for python3. Use this version for python 2:
https://github.com/croxis/SpaceDrive/blob/233c842e0f2bc54eb9af792de8860390d65580c6/spacedrive/surface_mesh.py

I'll work on something a little more graceful.

On Wed, Jun 29, 2016 at 12:49 AM, sazearte notifications@github.com wrote:

> Panda with Python 2.7
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/croxis/SpaceDrive/issues/1#issuecomment-229282244,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAHa94Kj-8tDhHsD4DMA4gR3myfr1C5Eks5qQiOHgaJpZM4I_3xJ
> .

## 
- David - Proud to be saving the world since 1984

**Comment by sazearte** [comment]
ok thank you.
It's possible for me to use Panda with Python 3 but your programme use renderPipeline, it's compatible with Python3 ?

**Comment by croxis** [comment]
Yes

**Comment by sazearte** [comment]
Ok, i have a problem with sandbox (with python 2.7 and 3.4)  :
in file systems.py, line 14, in <module>
class EntitySystem(object, DirectObject):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, DirectObject

Have you this error ?

**Comment by croxis** [comment]
Can you also tell me what version of panda you are using

**Comment by sazearte** [comment]
Panda3D-SDK-1.10.0pre-4283a63-py3.4-x64

the last beta build, in Windows 10 64bits.

**Comment by sazearte** [comment]
which version are you using?

**Comment by croxis** [comment]
I'm using HEAD. I just updated the pipeline and am running into some issues. As soon as I get these new issues fixed I'll continue on this bug.

**Comment by croxis** [comment]
Can you also post a minimal script that replicates the error?

**Comment by sazearte** [comment]
yes, this is my code :

```
import spacedrive

if __name__ == '__main__':
    # Configure any panda prc settings here
    spacedrive.init(log_level='info', window_title='SpaceDrive Demo')
    # Initiate the game loop.
    spacedrive.run()
```

my complete error :
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import spacedrive
  File "F:\Panda\SpaceDrive\spacedrive__init__.py", line 6, in <module>
    import sandbox
  File "F:\Panda\Panda3D3-1.10.1-x64\Panda3D-1.10.0-x64\python\lib\sandbox__init__.py", line 12, in <module>
    from .networking import UDPNetworkSystem
  File "F:\Panda\Panda3D3-1.10.1-x64\Panda3D-1.10.0-x64\python\lib\sandbox\networking.py", line 12, in <module>
    from .systems import EntitySystem
  File "F:\Panda\Panda3D3-1.10.1-x64\Panda3D-1.10.0-x64\python\lib\sandbox\systems.py", line 14, in <module>
    class EntitySystem(object, DirectObject):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases DirectObject, object

```
```

**Comment by croxis** [comment]
Fixed the issue. There is another bug that will crop up with SpaceDrive that I am fixing right now so I will leave this issue open.

**Comment by croxis** [comment]
And fixed. Please open more issues if you run into problems. I also hang out in the #panda3d irc channel on freenode.net
